### ISSUE TITLE
crud-mysql-app-reference

### ISSUE THREAD

**Issue by MathieuGAUBAL** [pierrehouot/crud-mysql-app-reference#1]
Chapeau Pierre ! ton home est super cool 😎
index.js => OK
index.js => OK
Il semble y avoir une erreur sur la méthode GET /wizards?'house || birthyear' ; il faudrait mettre valuesToEscape à la place de house pour que ça fonctionne. 
```
  connection.promise().query(sql, [valuesToEscape])
    .then(([results]) => {
      res.json(results)
    })
```
les méthodes PATCH / PUT / DELETE devraient exécuter un GET pour rechercher la ressource (si elle existe) puis la supprimer avec DELETE

**Comment by pierrehouot** [comment]
Coucou Mathieu, tu peux me dire si j'ai tout fix ? :)
Merci beaucoup pour tes retours !
